import turtle

turtle.shape('turtle')
for i in range (10):
    turtle.penup()
    turtle.forward (i*6)
    turtle.pendown()
    turtle.left(90)
    turtle.forward(i*6)
    turtle.left(90)
    turtle.forward(i*12)
    turtle.left(90)
    turtle.forward(i*12)
    turtle.left(90)
    turtle.forward(i*12)
    turtle.left(90)
    turtle.forward(i*6)
    turtle.penup()
    turtle.left(90)
    turtle.forward(i*6)
    turtle.left(180)
